$RNFirebaseAsStaticFramework = true
# Override Firebase SDK Version
$FirebaseSDKVersion = '7.7.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod "Firebase/Firestore"
pod "Firebase/CoreOnly"
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
target 'FilmUi' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  target 'FilmUiTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'FilmUi-tvOS' do
  # Pods for FilmUi-tvOS

  target 'FilmUi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
